### ISSUE TITLE
Stuck at block 0. 

### ISSUE THREAD

**Issue by martivo** [Eurobit-Project/Eurobit#2]
Hi, 

It won't sync. In blog github instructions are mentioned for this case, but I don't see any. Tried latest release and also compile from source. Same result. Tried reseting the .eurobit folder too.

2018-Feb-09 17:26:55.652276 INFO    SYNCHRONIZATION started
2018-Feb-09 17:26:56.405574 WARNING CHECKPOINT FAILED FOR HEIGHT 100. EXPECTED HASH: ce75a54d6db6bcb05571b1b66f263eaa8184da733ca56ce7304fd114ac0564e7, FETCHED HASH: d70bca0482eb744536a37103d58de0c25fd19032676826ea3070f20077183d8e
2018-Feb-09 17:26:56.405676 WARNING Checkpoint block hash mismatch for block d70bca0482eb744536a37103d58de0c25fd19032676826ea3070f20077183d8e
2018-Feb-09 17:27:05.750005 INFO    [62.16.160.137:8080 OUT] Sync data returned unknown top block: 100 -> 3209 [3109 blocks (4 days) behind]
2018-Feb-09 17:27:05.750005 INFO    SYNCHRONIZATION started
2018-Feb-09 17:27:06.010768 WARNING CHECKPOINT FAILED FOR HEIGHT 100. EXPECTED HASH: ce75a54d6db6bcb05571b1b66f263eaa8184da733ca56ce7304fd114ac0564e7, FETCHED HASH: d70bca0482eb744536a37103d58de0c25fd19032676826ea3070f20077183d8e

**Comment by Codex02** [comment]
We recently just commented all of the checkpoints, which is what seems to be causing this error, we've seen this a fair few time and we are commenting the checkpoints for now until the chain is at a higher height, then we will add checkpoints back. If you compile from the current source, it should work.

**Comment by martivo** [comment]
Latest git pull indeed solved the problem, "make clean" also solved the problem of me having a wallet with coins in it.  Oh well...
